/**
 * Assembles the generated rules module.
 *
 * What comes out is the whole of the rules as TypeScript: a function per
 * program, a switch per dispatch decision, and read only tables for weights,
 * character sets and remainder maps. The published package carries this file
 * and the primitives it calls, and nothing else — no bundle, no decoder, no
 * interpreter.
 */
import { ChecksumOpKind, ProgramKind } from "../../../generated/entid/ir/v1/rules_pb.js";
import { GeneratorError } from "../errors.js";
import type { IrDefinition, IrDispatcher, IrProgram, LoadedBundle } from "../ir.js";
import { type EmitContext, stringExpression } from "./expression.js";
import { analyseNeeds, type ProgramNeeds } from "./needs.js";
import { chooseBody, programBody } from "./program.js";
import { ConstantPool, HelperPool } from "./pool.js";

import { codePointsOf } from "../../../src/runtime/text.js";

const quote = (value: string): string => JSON.stringify(value);
const indent = (lines: readonly string[]): string[] =>
  lines.map((line) => (line === "" ? line : `  ${line}`));

const HEADER = `// Code generated by tools/generator. DO NOT EDIT.
// Run \`pnpm generate\` after any change to spec/ or to rules.lock.
/* eslint-disable */`;

interface Emitted {
  readonly source: string;
  readonly kinds: readonly string[];
}

/**
 * Where the emitted module finds the primitives it calls.
 *
 * The shipped rules sit beside `src/`, so the default is a plain relative
 * prefix. A test that generates rules into a scratch directory points this at
 * the same modules from wherever it writes them.
 */
export interface EmitOptions {
  readonly importPrefix?: string;
}

function nameOf(program: IrProgram): string {
  const prefix =
    program.kind === ProgramKind.CANONICALIZATION
      ? "canon"
      : program.kind === ProgramKind.FORMAT
        ? "format"
        : "checksum";
  return `${prefix}${String(program.id)}`;
}

/** The parameters a program's function declares, in a fixed order. */
function parameters(program: IrProgram, needs: ProgramNeeds): string[] {
  const out: string[] = [];
  if (program.kind !== ProgramKind.CANONICALIZATION && needs.subject) {
    out.push("subject: StringValue");
  }
  if (program.kind === ProgramKind.CANONICALIZATION || needs.value) {
    out.push("value: readonly number[]");
  }
  if (needs.definition) {
    out.push("definition: number");
  }
  if (needs.profile) {
    out.push("profile: ValidationProfile");
  }
  return out;
}

/** The arguments a call to that program passes, matching `parameters`. */
function callArguments(
  program: IrProgram,
  needs: ProgramNeeds,
  subject: string,
  value: string,
  definition: string,
  profile: string,
): string {
  const out: string[] = [];
  if (program.kind !== ProgramKind.CANONICALIZATION && needs.subject) {
    out.push(subject);
  }
  if (program.kind === ProgramKind.CANONICALIZATION || needs.value) {
    out.push(value);
  }
  if (needs.definition) {
    out.push(definition);
  }
  if (needs.profile) {
    out.push(profile);
  }
  return out.join(", ");
}

const returnTypeOf = (program: IrProgram): string =>
  program.kind === ProgramKind.CANONICALIZATION
    ? "readonly number[]"
    : program.kind === ProgramKind.FORMAT
      ? "AssertionResult"
      : "ChecksumOutcome";

/** Emits the rules module for a bundle that passed every check. */
export function emitModule(bundle: LoadedBundle, options: EmitOptions = {}): Emitted {
  const from = options.importPrefix ?? "./";
  const constants = new ConstantPool();
  const helpers = new HelperPool();
  const needs = analyseNeeds(bundle);

  const needsOf = (programId: number): ProgramNeeds => {
    const found = needs.get(programId);
    if (found === undefined) {
      throw new GeneratorError(`no needs computed for program ${String(programId)}`);
    }
    return found;
  };

  const programs = [...bundle.programs.values()].sort((left, right) => left.id - right.id);
  const programSource = programs
    .flatMap((program) => emitProgram(bundle, program, needsOf, constants, helpers))
    .join("\n");

  // An accessor the rules never call would be an unused declaration, so each
  // one is emitted only when the generated programs reach for it.
  const accessors = [
    ...(programSource.includes("countryPointsOf(") ? emitCountryPoints(bundle, constants) : []),
    ...(programSource.includes("acceptedPrefixesOf(")
      ? emitAcceptedPrefixes(bundle, constants)
      : []),
    ...(programSource.includes("prependedPrefixOf(") ? emitPrependedPrefix(bundle, constants) : []),
  ];

  const kinds = [...bundle.kindIndex.keys()].sort();
  const source = [
    HEADER,
    "",
    `import type { ValidationProfile } from "${from}domain/profile.js";`,
    `import * as support from "${from}runtime/support.js";`,
    `import type { AssertionResult, ChecksumOutcome, StringValue } from "${from}runtime/values.js";`,
    "",
    "/** The business version of the rules this module was generated from. */",
    `export const RULES_VERSION = ${quote(bundle.rulesVersion)};`,
    "",
    "/** The structural version of the IR this module was generated from. */",
    `export const FORMAT_VERSION = ${String(bundle.formatVersion)};`,
    "",
    "/** The capability ids the bundle required, ascending. */",
    `export const CAPABILITIES: readonly number[] = [${[...bundle.capabilities]
      .sort((left, right) => left - right)
      .join(", ")}];`,
    "",
    "/** Every kind token these rules route, canonical kinds and aliases alike. */",
    `export const KINDS: readonly string[] = [${kinds.map(quote).join(", ")}];`,
    "",
    ...constants.declarations(),
    "",
    ...helpers.declarations(),
    "",
    ...accessors,
    "",
    programSource,
    "",
    ...emitDispatch(bundle),
    "",
    ...emitDefinitionMetadata(bundle),
    "",
    ...emitEntries(bundle, needsOf),
    "",
  ].join("\n");

  return { source, kinds };
}

/* -------------------------------------------------------------------------- */
/* Programs                                                                   */
/* -------------------------------------------------------------------------- */

function emitProgram(
  bundle: LoadedBundle,
  program: IrProgram,
  needsOf: (programId: number) => ProgramNeeds,
  constants: ConstantPool,
  helpers: HelperPool,
): string[] {
  const own = needsOf(program.id);
  const isCanonicalization = program.kind === ProgramKind.CANONICALIZATION;
  const local = isCanonicalization ? "current" : "value";

  const context: EmitContext = {
    constants,
    helpers,
    program,
    value: isCanonicalization ? local : "value",
    subject: isCanonicalization ? undefined : "subject",
    definition: "definition",
    profile: "profile",
    nameOf: (programId) => {
      const callee = bundle.programs.get(programId);
      if (callee === undefined) {
        throw new GeneratorError(`call towards unknown program ${String(programId)}`);
      }
      return nameOf(callee);
    },
    argumentsOf: (programId, subject) => {
      const callee = bundle.programs.get(programId);
      if (callee === undefined) {
        throw new GeneratorError(`call towards unknown program ${String(programId)}`);
      }
      return callArguments(callee, needsOf(programId), subject, "value", "definition", "profile");
    },
    chooseOf: (nodeIndex) => `choose${String(program.id)}_${String(nodeIndex)}`,
    chooseArguments: callArguments(program, own, "subject", "value", "definition", "profile"),
  };

  const blocks: string[] = [];

  // Every CHOOSE becomes its own function: its branches are statements, and a
  // WHEN predicate is a condition rather than a value.
  for (const [index, node] of program.nodes.entries()) {
    if (node.operation.family !== "checksum" || node.operation.kind !== ChecksumOpKind.CHOOSE) {
      continue;
    }
    if (index === program.rootNode) {
      continue;
    }
    blocks.push(
      `function ${context.chooseOf(index)}(${parameters(program, own).join(", ")}): ChecksumOutcome {`,
      ...indent(chooseBody(context, index)),
      `}`,
      "",
    );
  }

  blocks.push(
    `function ${nameOf(program)}(${parameters(program, own).join(", ")}): ${returnTypeOf(program)} {`,
    ...indent(programBody(context, program, local)),
    `}`,
    "",
  );
  return blocks;
}

/* -------------------------------------------------------------------------- */
/* Definition accessors                                                       */
/* -------------------------------------------------------------------------- */

const pointsOf = (value: string): number[] => codePointsOf(value);

function emitCountryPoints(bundle: LoadedBundle, constants: ConstantPool): string[] {
  const cases = [...bundle.definitions.values()]
    .filter((definition) => definition.countryCode !== undefined)
    .map(
      (definition) =>
        `    case ${String(definition.id)}:\n      return ${constants.codePoints(pointsOf(definition.countryCode ?? ""))};`,
    );
  return [
    "/**",
    " * The country of the target a definition belongs to, as code points.",
    " *",
    " * Absent for a GLOBAL definition, which has no country: `country_code()`",
    " * yields the absent string there, even though the report may still carry the",
    " * normalized country context the caller supplied.",
    " */",
    "function countryPointsOf(definition: number): readonly number[] | undefined {",
    "  switch (definition) {",
    ...cases,
    "    default:",
    "      return undefined;",
    "  }",
    "}",
  ];
}

function emitAcceptedPrefixes(bundle: LoadedBundle, constants: ConstantPool): string[] {
  const cases: string[] = [];
  for (const dispatcher of bundle.dispatchers.values()) {
    for (const target of dispatcher.targets) {
      const names = target.acceptedPrefixes.map((prefix) => constants.codePoints(pointsOf(prefix)));
      cases.push(
        `    case ${String(target.definitionId)}:\n      return ${constants.prefixes(names)};`,
      );
    }
  }
  return [
    "/** The prefixes the target of a definition accepts. */",
    "function acceptedPrefixesOf(definition: number): readonly (readonly number[])[] {",
    "  switch (definition) {",
    ...cases,
    "    default:",
    `      return ${constants.prefixes([])};`,
    "  }",
    "}",
  ];
}

function emitPrependedPrefix(bundle: LoadedBundle, constants: ConstantPool): string[] {
  const cases: string[] = [];
  for (const dispatcher of bundle.dispatchers.values()) {
    for (const target of dispatcher.targets) {
      // The canonical prefix when the target declares one, otherwise its
      // country: the business prefix and the ISO code differ for some targets.
      const prefix = target.canonicalPrefix ?? target.countryCode;
      if (prefix === undefined) {
        continue;
      }
      cases.push(
        `    case ${String(target.definitionId)}:\n      return ${constants.codePoints(pointsOf(prefix))};`,
      );
    }
  }
  return [
    "/**",
    " * The prefix `prepend_country_if_missing` adds for a definition.",
    " *",
    " * The canonical prefix of its target when one is declared, otherwise the",
    " * country code, because a business prefix may differ from the ISO code.",
    " */",
    "function prependedPrefixOf(definition: number): readonly number[] {",
    "  switch (definition) {",
    ...cases,
    "    default:",
    `      return ${constants.codePoints([])};`,
    "  }",
    "}",
  ];
}

/* -------------------------------------------------------------------------- */
/* Dispatch                                                                   */
/* -------------------------------------------------------------------------- */

function emitDispatch(bundle: LoadedBundle): string[] {
  const dispatchers = [...bundle.dispatchers.values()];
  const indexOf = new Map<string, number>(
    dispatchers.map((dispatcher, index) => [dispatcher.kind, index]),
  );

  const kindCases: string[] = [];
  for (const [token, dispatcher] of [...bundle.kindIndex.entries()].sort()) {
    kindCases.push(
      `    case ${quote(token)}:\n      return ${String(indexOf.get(dispatcher.kind) ?? -1)};`,
    );
  }

  const lines: string[] = [
    "/**",
    " * The dispatcher a normalized kind token selects, or -1.",
    " *",
    " * Canonical kinds and their aliases share one space, which the loader proved",
    " * holds no collision, so a single switch decides it.",
    " */",
    "export function dispatcherOf(kind: string): number {",
    "  switch (kind) {",
    ...kindCases,
    "    default:",
    "      return -1;",
    "  }",
    "}",
    "",
    "/** The canonical kind of a dispatcher. */",
    "export function canonicalKindOf(dispatcher: number): string {",
    "  switch (dispatcher) {",
    ...dispatchers.map(
      (dispatcher, index) => `    case ${String(index)}:\n      return ${quote(dispatcher.kind)};`,
    ),
    "    default:",
    `      return "";`,
    "  }",
    "}",
    "",
    "/** Runs the pre-canonicalization program of a dispatcher, exactly once. */",
    "export function preCanonicalize(dispatcher: number, value: readonly number[]): readonly number[] {",
    "  switch (dispatcher) {",
    ...dispatchers.map((dispatcher, index) => {
      const program = bundle.programs.get(dispatcher.preCanonicalizationProgram);
      if (program === undefined) {
        throw new GeneratorError(`dispatcher ${dispatcher.kind} has no pre-canonicalizer`);
      }
      return `    case ${String(index)}:\n      return ${nameOf(program)}(value);`;
    }),
    "    default:",
    "      return value;",
    "  }",
    "}",
    "",
    "/** Normalizes a country token through the alias table of a dispatcher. */",
    "export function aliasCountry(dispatcher: number, country: string): string {",
    "  switch (dispatcher) {",
    ...dispatchers.flatMap((dispatcher, index) => {
      if (dispatcher.countryAliases.size === 0) {
        return [];
      }
      return [
        `    case ${String(index)}:`,
        `      switch (country) {`,
        ...[...dispatcher.countryAliases.entries()].map(
          ([alias, canonical]) =>
            `        case ${quote(alias)}:\n          return ${quote(canonical)};`,
        ),
        `        default:`,
        `          return country;`,
        `      }`,
      ];
    }),
    "    default:",
    "      return country;",
    "  }",
    "}",
    "",
    "/** The definition a country selects within a dispatcher, or -1. */",
    "export function definitionForCountry(dispatcher: number, country: string): number {",
    "  switch (dispatcher) {",
    ...dispatchers.flatMap((dispatcher, index) => {
      if (dispatcher.targetsByCountry.size === 0) {
        return [];
      }
      return [
        `    case ${String(index)}:`,
        `      switch (country) {`,
        ...[...dispatcher.targetsByCountry.entries()].map(
          ([country, target]) =>
            `        case ${quote(country)}:\n          return ${String(target.definitionId)};`,
        ),
        `        default:`,
        `          return -1;`,
        `      }`,
      ];
    }),
    "    default:",
    "      return -1;",
    "  }",
    "}",
    "",
    "/**",
    " * The definition the longest accepted prefix of a value selects, or -1.",
    " *",
    " * Prefixes are declared ASCII, so a value whose head is not ASCII matches",
    " * nothing. The loader proved no prefix belongs to two targets, so the longest",
    " * match is the only decision to make.",
    " */",
    "export function definitionForPrefix(dispatcher: number, value: readonly number[]): number {",
    "  switch (dispatcher) {",
    ...dispatchers.flatMap((dispatcher, index) => emitPrefixCase(dispatcher, index)),
    "    default:",
    "      return -1;",
    "  }",
    "}",
    "",
    "/** The GLOBAL target of a dispatcher, or -1. */",
    "export function globalDefinitionOf(dispatcher: number): number {",
    "  switch (dispatcher) {",
    ...dispatchers.flatMap((dispatcher, index) =>
      dispatcher.globalTarget === undefined
        ? []
        : [
            `    case ${String(index)}:\n      return ${String(dispatcher.globalTarget.definitionId)};`,
          ],
    ),
    "    default:",
    "      return -1;",
    "  }",
    "}",
    "",
    "/** The single target selectable with neither country nor prefix, or -1. */",
    "export function implicitDefinitionOf(dispatcher: number): number {",
    "  switch (dispatcher) {",
    ...dispatchers.flatMap((dispatcher, index) =>
      dispatcher.implicitTarget === undefined
        ? []
        : [
            `    case ${String(index)}:\n      return ${String(dispatcher.implicitTarget.definitionId)};`,
          ],
    ),
    "    default:",
    "      return -1;",
    "  }",
    "}",
  ];
  return lines;
}

function emitPrefixCase(dispatcher: IrDispatcher, index: number): string[] {
  if (dispatcher.targetsByPrefix.size === 0) {
    return [];
  }
  const byLength = new Map<number, [string, number][]>();
  for (const [prefix, target] of dispatcher.targetsByPrefix) {
    // Counted in code points, like every length the IR states. A prefix is
    // proven ASCII by the loader, so the two agree, but the abstraction is what
    // keeps that a fact rather than an assumption.
    const length = codePointsOf(prefix).length;
    const bucket = byLength.get(length) ?? [];
    bucket.push([prefix, target.definitionId]);
    byLength.set(length, bucket);
  }
  const lengths = [...byLength.keys()].sort((left, right) => right - left);
  const lines: string[] = [`    case ${String(index)}: {`];
  for (const length of lengths) {
    lines.push(
      `      const head${String(length)} = support.prefixString(value, ${String(length)});`,
      `      switch (head${String(length)}) {`,
      ...(byLength.get(length) ?? []).map(
        ([prefix, definitionId]) =>
          `        case ${quote(prefix)}:\n          return ${String(definitionId)};`,
      ),
      `        default:`,
      `          break;`,
      `      }`,
    );
  }
  lines.push(`      return -1;`, `    }`);
  return lines;
}

/* -------------------------------------------------------------------------- */
/* Definitions and entry points                                               */
/* -------------------------------------------------------------------------- */

function emitDefinitionMetadata(bundle: LoadedBundle): string[] {
  const definitions = [...bundle.definitions.values()].sort((left, right) => left.id - right.id);
  return [
    "/** The country a definition reports, absent for a GLOBAL definition. */",
    "export function countryOf(definition: number): string | undefined {",
    "  switch (definition) {",
    ...definitions.flatMap((definition) =>
      definition.countryCode === undefined
        ? []
        : [`    case ${String(definition.id)}:\n      return ${quote(definition.countryCode)};`],
    ),
    "    default:",
    "      return undefined;",
    "  }",
    "}",
    "",
    "/**",
    " * The profile a definition applies when the caller states none.",
    " *",
    " * Leaving the profile out is not the same request as passing `compatible`:",
    " * absence is what lets this default apply.",
    " */",
    "export function profileOf(definition: number): ValidationProfile {",
    "  switch (definition) {",
    ...definitions.flatMap((definition) =>
      definition.defaultProfile === "compatible"
        ? []
        : [`    case ${String(definition.id)}:\n      return ${quote(definition.defaultProfile)};`],
    ),
    "    default:",
    `      return "compatible";`,
    "  }",
    "}",
  ];
}

function emitEntries(bundle: LoadedBundle, needsOf: (programId: number) => ProgramNeeds): string[] {
  const definitions = [...bundle.definitions.values()].sort((left, right) => left.id - right.id);

  const entry = (definition: IrDefinition, programId: number, subject: string): string => {
    const program = bundle.programs.get(programId);
    if (program === undefined) {
      throw new GeneratorError(`definition ${String(definition.id)} references a missing program`);
    }
    const args = callArguments(
      program,
      needsOf(programId),
      subject,
      "value",
      String(definition.id),
      "profile",
    );
    return `${nameOf(program)}(${args})`;
  };

  /** The subject a top level invocation starts from. */
  const topSubject = (programId: number): string => {
    const program = bundle.programs.get(programId);
    if (program?.subjectNode === undefined) {
      return "value";
    }
    const context: EmitContext = {
      constants: new ConstantPool(),
      helpers: new HelperPool(),
      program,
      value: "value",
      // A program that computes its own subject cannot read subject() to do it.
      subject: undefined,
      definition: "definition",
      profile: "profile",
      nameOf: () => {
        throw new GeneratorError("a call inside a subject default");
      },
      argumentsOf: () => {
        throw new GeneratorError("a call inside a subject default");
      },
      chooseOf: () => {
        throw new GeneratorError("a choose inside a subject default");
      },
      chooseArguments: "",
    };
    return stringExpression(context, program.subjectNode);
  };

  /*
   * The exported entries keep one shape whatever the rules need, because the
   * pipeline calls them the same way for every definition. A profile no rule
   * reads is named with a leading underscore rather than dropped: changing the
   * arity would make the call site depend on which rules happen to ship.
   */
  const profileName = (bodies: readonly string[]): string =>
    bodies.some((body) => /\bprofile\b/.test(body)) ? "profile" : "_profile";

  const canonicalCases = definitions.map(
    (definition) =>
      `    case ${String(definition.id)}:\n      return ${entry(definition, definition.canonicalizationProgram, "value")};`,
  );
  const formatCases = definitions.map(
    (definition) =>
      `    case ${String(definition.id)}:\n      return ${entry(definition, definition.formatProgram, topSubject(definition.formatProgram))};`,
  );
  const checksumCases = definitions.map((definition) => {
    const reported =
      definition.checksumProgram === undefined
        ? outcomeLiteral(definition.absentChecksumReason)
        : entry(definition, definition.checksumProgram, topSubject(definition.checksumProgram));
    return `    case ${String(definition.id)}:\n      return ${reported};`;
  });

  return [
    "/** Runs the canonicalization program of a definition, exactly once. */",
    "export function canonicalizeWith(",
    "  definition: number,",
    "  value: readonly number[],",
    `  ${profileName(canonicalCases)}: ValidationProfile,`,
    "): readonly number[] {",
    "  switch (definition) {",
    ...canonicalCases,
    "    default:",
    "      return value;",
    "  }",
    "}",
    "",
    "/** Runs the format rule of a definition on its canonical value. */",
    "export function checkFormat(",
    "  definition: number,",
    "  value: readonly number[],",
    `  ${profileName(formatCases)}: ValidationProfile,`,
    "): AssertionResult {",
    "  switch (definition) {",
    ...formatCases,
    "    default:",
    "      return support.PASSED;",
    "  }",
    "}",
    "",
    "/**",
    " * Runs the checksum rule of a definition, or reports why none applies.",
    " *",
    " * A definition either declares a program or declares the reason no algorithm",
    " * is available, never both and never neither, which the loader proved.",
    " */",
    "export function checkChecksum(",
    "  definition: number,",
    "  value: readonly number[],",
    `  ${profileName(checksumCases)}: ValidationProfile,`,
    "): ChecksumOutcome {",
    "  switch (definition) {",
    ...checksumCases,
    "    default:",
    "      return support.UNSUPPORTED_CHECKSUM;",
    "  }",
    "}",
  ];
}

function outcomeLiteral(reasonCode: string | undefined): string {
  if (reasonCode === undefined || reasonCode === "unsupported_checksum") {
    return "support.UNSUPPORTED_CHECKSUM";
  }
  return `{ status: "unsupported", reasonCode: ${quote(reasonCode)} }`;
}
