#!/usr/bin/env node
/**
 * Emits the generated assets of the package from the attested spec artifacts.
 *
 * The runtime must reach the official bundle synchronously, in a browser as
 * well as in Node, without a fetch or a filesystem read. The bundle is
 * therefore inlined as a `Uint8Array` built from the exact bytes of
 * `businessid-rules.binpb`. Base64 is deliberately not used: the canonical
 * form is the byte sequence itself.
 *
 * This script may use Node APIs. The published runtime may not.
 *
 * Run with `--check` to verify that the files on disk match what this script
 * would emit, which is what CI enforces.
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const checkOnly = process.argv.includes("--check");

const HEADER = `// Code generated by scripts/generate.mjs. DO NOT EDIT.\n`;

function sha256(bytes) {
  return createHash("sha256").update(bytes).digest("hex");
}

/** Reads the digests `rules.lock` attests. */
function readLock() {
  const text = readFileSync(join(root, "rules.lock"), "utf8");
  const entries = new Map();
  for (const line of text.split("\n")) {
    const match = /^(\w+)\s*=\s*"?([^"\n]*)"?\s*$/.exec(line.trim());
    if (match && !line.trim().startsWith("#")) {
      entries.set(match[1], match[2]);
    }
  }
  return entries;
}

/* -------------------------------------------------------------------------- */
/* Minimal wire reader                                                        */
/*                                                                            */
/* The generator reads the bundle only to list the dispatcher kinds it        */
/* declares. It stays at the wire level and deliberately shares no code with  */
/* the runtime loader, so a defect in one cannot hide itself in the other.    */
/* -------------------------------------------------------------------------- */

function readFields(view) {
  let offset = 0;
  const fields = new Map();
  const varint = () => {
    let result = 0n;
    let shift = 0n;
    for (;;) {
      const byte = view[offset];
      offset += 1;
      if (byte === undefined) {
        throw new Error("truncated varint");
      }
      result |= BigInt(byte & 0x7f) << shift;
      if ((byte & 0x80) === 0) {
        return result;
      }
      shift += 7n;
    }
  };
  while (offset < view.length) {
    const key = Number(varint());
    const field = key >>> 3;
    const wire = key & 7;
    let value;
    if (wire === 0) {
      value = varint();
    } else if (wire === 1) {
      value = view.subarray(offset, offset + 8);
      offset += 8;
    } else if (wire === 2) {
      const length = Number(varint());
      value = view.subarray(offset, offset + length);
      offset += length;
    } else if (wire === 5) {
      value = view.subarray(offset, offset + 4);
      offset += 4;
    } else {
      throw new Error(`unsupported wire type ${wire}`);
    }
    const bucket = fields.get(field);
    if (bucket) {
      bucket.push(value);
    } else {
      fields.set(field, [value]);
    }
  }
  return fields;
}

const decoder = new TextDecoder("utf-8", { fatal: true });

/** Lists every kind token the bundle routes: canonical kinds and their aliases. */
function kindsOf(bundle) {
  const kinds = new Set();
  for (const dispatcher of readFields(bundle).get(8) ?? []) {
    const fields = readFields(dispatcher);
    for (const kind of fields.get(1) ?? []) {
      kinds.add(decoder.decode(kind));
    }
    for (const alias of fields.get(2) ?? []) {
      kinds.add(decoder.decode(alias));
    }
  }
  return [...kinds].sort();
}

/* -------------------------------------------------------------------------- */
/* Emitters                                                                   */
/* -------------------------------------------------------------------------- */

function renderBytes(bytes) {
  const lines = [];
  const perLine = 24;
  for (let index = 0; index < bytes.length; index += perLine) {
    lines.push(`  ${[...bytes.subarray(index, index + perLine)].join(", ")},`);
  }
  return lines.join("\n");
}

function renderRulesModule(bytes, digest, rulesVersion, formatVersion) {
  return `${HEADER}
/**
 * The official rule bundle, inlined as the exact bytes of
 * \`businessid-rules.binpb\`.
 *
 * Rules version \`${rulesVersion}\`, IR format version ${formatVersion}.
 * SHA-256 \`${digest}\`, verified against \`rules.lock\` when this file was
 * generated and again by \`check:generated\` in CI.
 */
export const RULES_BUNDLE_BYTES: Uint8Array = new Uint8Array([
${renderBytes(bytes)}
]);

/** The rules version the inlined bundle announces. */
export const RULES_VERSION = ${JSON.stringify(rulesVersion)};

/** The IR format version the inlined bundle announces. */
export const RULES_FORMAT_VERSION = ${formatVersion};

/** The SHA-256 of the inlined bundle, as attested by \`rules.lock\`. */
export const RULES_SHA256 = ${JSON.stringify(digest)};
`;
}

function renderVersionModule(version) {
  return `${HEADER}
/**
 * The version of this package.
 *
 * Reported as \`engineVersion\` and generated from \`package.json\`, because the
 * runtime cannot read a file: it must work in a browser as well as in Node.
 * Conformance never compares this field between engines.
 */
export const ENGINE_VERSION = ${JSON.stringify(version)};
`;
}

function renderKindsModule(kinds) {
  return `${HEADER}
/**
 * Every kind token the inlined bundle routes, canonical kinds and aliases
 * alike.
 *
 * Offered for completion only. \`IdentifierKind\` accepts any string, because a
 * caller may legitimately pass a token this build has never heard of and must
 * receive \`unsupported_kind\` rather than a compile error.
 */
export const KNOWN_IDENTIFIER_KINDS = [
${kinds.map((kind) => `  ${JSON.stringify(kind)},`).join("\n")}
] as const;
`;
}

/* -------------------------------------------------------------------------- */

function emit(relativePath, contents) {
  const path = join(root, relativePath);
  let current = null;
  try {
    current = readFileSync(path, "utf8");
  } catch {
    current = null;
  }
  if (current === contents) {
    return { path: relativePath, changed: false };
  }
  if (!checkOnly) {
    writeFileSync(path, contents);
  }
  return { path: relativePath, changed: true };
}

function main() {
  const lock = readLock();
  const bundlePath = join(root, "spec", "businessid-rules.binpb");
  const bundle = readFileSync(bundlePath);
  const digest = sha256(bundle);

  const expected = lock.get("rules_sha256");
  if (digest !== expected) {
    throw new Error(
      `spec/businessid-rules.binpb does not match rules.lock\n  expected ${expected}\n  actual   ${digest}`,
    );
  }

  const corpusPath = join(root, "spec", "businessid-conformance.binpb");
  const corpusDigest = sha256(readFileSync(corpusPath));
  const expectedCorpus = lock.get("conformance_sha256");
  if (corpusDigest !== expectedCorpus) {
    throw new Error(
      `spec/businessid-conformance.binpb does not match rules.lock\n  expected ${expectedCorpus}\n  actual   ${corpusDigest}`,
    );
  }

  const fields = readFields(bundle);
  const formatVersion = Number(fields.get(1)?.[0] ?? 0n);
  const rulesVersion = decoder.decode(fields.get(2)?.[0] ?? new Uint8Array());
  if (rulesVersion !== lock.get("rules_version")) {
    throw new Error(
      `bundle announces rules version ${rulesVersion}, rules.lock says ${lock.get("rules_version")}`,
    );
  }
  if (formatVersion !== Number(lock.get("format_version"))) {
    throw new Error(
      `bundle announces format version ${formatVersion}, rules.lock says ${lock.get("format_version")}`,
    );
  }

  const results = [
    emit(
      "src/assets/rules.generated.ts",
      renderRulesModule(bundle, digest, rulesVersion, formatVersion),
    ),
    emit("src/assets/kinds.generated.ts", renderKindsModule(kindsOf(bundle))),
    emit(
      "src/assets/version.generated.ts",
      renderVersionModule(JSON.parse(readFileSync(join(root, "package.json"), "utf8")).version),
    ),
  ];

  const stale = results.filter((result) => result.changed);
  if (checkOnly) {
    if (stale.length > 0) {
      console.error("Generated files are out of date:");
      for (const result of stale) {
        console.error(`  ${result.path}`);
      }
      console.error("Run `pnpm generate`.");
      process.exit(1);
    }
    console.log(`check:generated ok (rules ${rulesVersion}, format ${formatVersion})`);
    return;
  }

  for (const result of results) {
    console.log(`${result.changed ? "wrote" : "unchanged"} ${result.path}`);
  }
}

main();
