/**
 * Runs the generator over the attested bundle and writes the generated files.
 *
 * This program may use Node freely; nothing it emits does. Run it with
 * `--check` to verify that what is on disk is what it would write, which is
 * what CI enforces.
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { generate } from "./generate.js";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const checkOnly = process.argv.includes("--check");

const HEADER = "// Code generated by tools/generator. DO NOT EDIT.\n";

/** Reads the digests `rules.lock` attests. */
function readLock(): Map<string, string> {
  const text = readFileSync(join(root, "rules.lock"), "utf8");
  const entries = new Map<string, string>();
  for (const line of text.split("\n")) {
    if (line.trim().startsWith("#")) {
      continue;
    }
    const match = /^(\w+)\s*=\s*"?([^"\n]*)"?\s*$/.exec(line.trim());
    if (match?.[1] !== undefined && match[2] !== undefined) {
      entries.set(match[1], match[2]);
    }
  }
  return entries;
}

function requireDigest(lock: Map<string, string>, key: string, path: string): Uint8Array {
  const bytes = readFileSync(path);
  const digest = createHash("sha256").update(bytes).digest("hex");
  const expected = lock.get(key);
  if (digest !== expected) {
    throw new Error(
      `${path} does not match rules.lock\n  expected ${String(expected)}\n  actual   ${digest}`,
    );
  }
  return new Uint8Array(bytes);
}

function renderKinds(kinds: readonly string[]): string {
  return `${HEADER}
/**
 * Every kind token the generated rules route, canonical kinds and aliases
 * alike.
 *
 * Offered for completion only. \`IdentifierKind\` accepts any string, because a
 * caller may legitimately pass a token this build has never heard of and must
 * receive \`unsupported_kind\` rather than a compile error.
 */
export const KNOWN_IDENTIFIER_KINDS = [
${kinds.map((kind) => `  ${JSON.stringify(kind)},`).join("\n")}
] as const;
`;
}

function renderVersion(version: string): string {
  return `${HEADER}
/**
 * The version of this package.
 *
 * Reported as \`engineVersion\` and generated from \`package.json\`, because the
 * runtime cannot read a file: it must work in a browser as well as in Node.
 * Conformance never compares this field between engines.
 */
export const ENGINE_VERSION = ${JSON.stringify(version)};
`;
}

function emit(relativePath: string, contents: string): boolean {
  const path = join(root, relativePath);
  let current: string | undefined;
  try {
    current = readFileSync(path, "utf8");
  } catch {
    current = undefined;
  }
  if (current === contents) {
    return false;
  }
  if (!checkOnly) {
    writeFileSync(path, contents);
  }
  return true;
}

function main(): void {
  const lock = readLock();
  const bundle = requireDigest(lock, "rules_sha256", join(root, "spec", "businessid-rules.binpb"));
  requireDigest(lock, "conformance_sha256", join(root, "spec", "businessid-conformance.binpb"));

  // `rules.lock` attests seven files and PROVENANCE.md asks for all seven to be
  // verified before starting. The two above are what this program reads; the
  // three schemas are re-verified by CI regenerating `generated/` and diffing
  // it, but the two documents were attested and checked by nothing. A lock
  // entry no one reads stops being a lock entry.
  for (const [key, name] of [
    ["rules_proto_sha256", "rules.proto"],
    ["conformance_proto_sha256", "conformance.proto"],
    ["testee_proto_sha256", "testee.proto"],
    ["ir_doc_sha256", "ir.md"],
    ["features_doc_sha256", "features.md"],
  ] as const) {
    requireDigest(lock, key, join(root, "spec", name));
  }

  const generated = generate(bundle);
  if (generated.rulesVersion !== lock.get("rules_version")) {
    throw new Error(
      `bundle announces rules version ${generated.rulesVersion}, rules.lock says ${String(lock.get("rules_version"))}`,
    );
  }
  if (String(generated.formatVersion) !== lock.get("format_version")) {
    throw new Error(
      `bundle announces format version ${String(generated.formatVersion)}, rules.lock says ${String(lock.get("format_version"))}`,
    );
  }

  const manifest = JSON.parse(readFileSync(join(root, "package.json"), "utf8")) as {
    version: string;
  };
  const written = [
    ["src/rules.generated.ts", generated.source],
    ["src/assets/kinds.generated.ts", renderKinds(generated.kinds)],
    ["src/assets/version.generated.ts", renderVersion(manifest.version)],
  ] as const;

  const stale = written.filter(([path, contents]) => emit(path, contents)).map(([path]) => path);

  if (checkOnly) {
    if (stale.length > 0) {
      console.error("Generated files are out of date:");
      for (const path of stale) {
        console.error(`  ${path}`);
      }
      console.error("Run `pnpm generate`.");
      process.exit(1);
    }
    console.log(
      `check:generated ok (rules ${generated.rulesVersion}, format ${String(generated.formatVersion)}, ${String(generated.capabilities.length)} capabilities)`,
    );
    return;
  }

  for (const [path] of written) {
    console.log(`wrote ${path}`);
  }
}

main();
