// Code generated by scripts/generate.mjs. DO NOT EDIT.

/**
 * The version of this package.
 *
 * Reported as `engineVersion` and generated from `package.json`, because the
 * runtime cannot read a file: it must work in a browser as well as in Node.
 * Conformance never compares this field between engines.
 */
export const ENGINE_VERSION = "0.1.0";
